name: deploy

on: push

permissions:
  issues: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Slak
      id: deployment_message
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: "infra"
        payload: |
          {
          	"blocks": [
          		{
          			"type": "section",
          			"text": {
          				"type": "mrkdwn",
          				"text": "You have a new request:\n*<fakeLink.toEmployeeProfile.com|Fred Enriquez - New device request>*"
          			}
          		},
          		{
          			"type": "section",
          			"fields": [
          				{
          					"type": "mrkdwn",
          					"text": "*Type:*\nComputer (laptop)"
          				},
          				{
          					"type": "mrkdwn",
          					"text": "*When:*\nSubmitted Aut 10"
          				},
          				{
          					"type": "mrkdwn",
          					"text": "*Last Update:*\nMar 10, 2015 (3 years, 5 months)"
          				},
          				{
          					"type": "mrkdwn",
          					"text": "*Reason:*\nAll vowel keys aren't working."
          				},
          				{
          					"type": "mrkdwn",
          					"text": "*Specs:*\n\"Cheetah Pro 15\" - Fast, really fast\""
          				}
          			]
          		},
          		{
          			"type": "actions",
          			"elements": [
          				{
          					"type": "button",
          					"text": {
          						"type": "plain_text",
          						"emoji": true,
          						"text": "Approve"
          					},
          					"style": "primary",
          					"value": "click_me_123",
          					"url": "https://www.google.com"
          				},
          				{
          					"type": "button",
          					"text": {
          						"type": "plain_text",
          						"emoji": true,
          						"text": "Deny"
          					},
          					"style": "danger",
          					"value": "click_me_123"
          				}
          			]
          		}
          	]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    - name: Approve
      id: manual-approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: youngwjung
        minimum-approvals: 1
        exclude-workflow-initiator-as-approver: false