name: deploy

on: push
    
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Slak
      id: deployment_message
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: "infra"
        payload: |
          {
          	"blocks": [
          		{
          			"type": "section",
          			"text": {
          				"type": "mrkdwn",
          				"text": "This is a section block with a button."
          			},
          			"accessory": {
          				"type": "button",
          				"text": {
          					"type": "plain_text",
          					"text": "Click Me",
          					"emoji": true
          				},
          				"value": "click_me_123",
          				"action_id": "button-action"
          			}
          		}
          	]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}